### ISSUE TITLE
when top to pull conmopenet is moving down

### ISSUE THREAD

**Issue by naseemakhtar994** [DuDigital/react-native-zoomable-view#20] opened 2019-09-06 07:20 UTC

**Comment by SNWStaff** [comment] 2019-10-21 12:50
Did you find a solution  ?

**Comment by SimonErich** [comment] 2019-10-28 13:31
@SNWStaff @naseemakhtar994 can you provide an example repo showcasing the problem, then I will have a look at it.

**Comment by SimonErich** [comment] 2019-12-09 18:07
Please elaborate more what you mean or what the problem is. I will close this for now. Feel free to open it again with a working example, that I can look at.

**Closed by SimonErich** 2019-12-09 18:07 UTC
