### ISSUE TITLE
deeper zoom scroll out or skip out

### ISSUE THREAD

**Issue by grappesm** [DuDigital/react-native-zoomable-view#24] opened 2019-11-22 13:24 UTC
I am displaying some large image inside. I set max Zoom to 5 (or higher). The first zoom with 2 fingers usually is OK. If I zoom more, the center point of zoom is moving out, or is zoom (with 2 fingers) again it is not easy zoom to point I want to. The point is moving away during zooming. Sometimes if I start second zoom (put 1st finger and after 1 second I puth the 2nd finger), the image skips.

**Comment by SimonErich** [comment] 2019-12-09 18:06
Could you please provide an example on expo or in a seperate repo, so I can see what the problem is?

**Comment by sugarman9907** [comment] 2020-03-11 06:43
I have same issue.

**Comment by dudyn5ky1** [comment] 2020-04-22 18:12
Any solution for this?

**Comment by SimonErich** [comment] 2020-11-23 12:45
Can you guys please provide a working for this.
You can use https://github.com/DuDigital/react-native-zoomable-view-example as a basis.
I am closing this for now. If you have the example, please open it again.

**Closed by SimonErich** 2020-11-23 12:45 UTC
Labels: more-info-needed
